package com.example.groupassignment;
import androidx.appcompat.app.AppCompatActivity;

import android.annotation.SuppressLint;
import android.database.Cursor;
import android.graphics.Paint;
import android.location.GnssAntennaInfo;
import android.net.sip.SipSession;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.CompoundButton;
import android.widget.EditText;
import android.widget.LinearLayout;



public class shopping_list extends AppCompatActivity {

    private SQLiteAdapter mySQLiteAdapter;
    View.OnClickListener listenerForAddCheckbox;
    CompoundButton.OnCheckedChangeListener listenerForCheckboxStateChange;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_shopping_list);


        //link xml components to program
        EditText inputItems = findViewById(R.id.et_input_items);
        Button btAdd = findViewById(R.id.bt_add);
        LinearLayout ll = findViewById(R.id.ll);

        //declare SQLite Adapter
        mySQLiteAdapter = new SQLiteAdapter(this);

        //define listener
        //listener for add button
        listenerForAddCheckbox = new View.OnClickListener() {

            @Override
            public void onClick(View v) {
                //open database to read data
                mySQLiteAdapter.openToWrite();

                //add new checkbox
                String item = inputItems.getText().toString();
                CheckBox item_checkbox = new CheckBox(shopping_list.this);
                item_checkbox.setText(item);
                ll.addView(item_checkbox);

                //insert data to database
                mySQLiteAdapter.insert(item);

                //close database
                mySQLiteAdapter.close();

                //clear the text area after adding new checkbox
                inputItems.setText("");

                // Add a listener to each CheckBox for state change
                item_checkbox.setOnCheckedChangeListener(listenerForCheckboxStateChange);


            }
        };
        //listener for checkbox state change(checked/unchecked)
        listenerForCheckboxStateChange = new CompoundButton.OnCheckedChangeListener() {
            @Override
            public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                //if checkbox is checked
                if (isChecked) {
                    // Get the content (text) of the item
                    String content = buttonView.getText().toString();

                    // Apply strikethrough to the text
                    buttonView.setPaintFlags(buttonView.getPaintFlags() | Paint.STRIKE_THRU_TEXT_FLAG);

                    // open database to write
                    mySQLiteAdapter.openToWrite();

                    // Delete the corresponding data from the database
                    mySQLiteAdapter.deleteItem(content);

                    //close database
                    mySQLiteAdapter.close();

                }
                //else checkbox is unchecked
                else {
                    // Remove the strikethrough effect
                    buttonView.setPaintFlags(buttonView.getPaintFlags() & (~Paint.STRIKE_THRU_TEXT_FLAG));

                    // Get the content (text) of the item
                    String content = buttonView.getText().toString();

                    //open database
                    mySQLiteAdapter.openToWrite();

                    //insert data to database
                    mySQLiteAdapter.insert(content);

                    //close database
                    mySQLiteAdapter.close();
                }
            }
        };

        //Retrieve Shopping List From Database And Make Them In Checkbox
        //open database to read data
        mySQLiteAdapter.openToRead();

        Cursor cursor = mySQLiteAdapter.getCursor();
        // Move the cursor to the first position in the database
        if (cursor.moveToFirst()) {
            do {
                // Get the content (text) of the item
                @SuppressLint("Range") String content = cursor.getString(cursor.getColumnIndex(SQLiteAdapter.KEY_CONTENT));

                CheckBox item_checkbox = new CheckBox(this);
                item_checkbox.setText(content);
                ll.addView(item_checkbox);

                // listener is add to the checkbox generated by the data from database
                item_checkbox.setOnCheckedChangeListener(listenerForCheckboxStateChange);

            } while (cursor.moveToNext());
        }

        //Activate the add button
        btAdd.setOnClickListener(listenerForAddCheckbox);

    }
}